name: telcabo
description: Telcabo


version: 1.0.0+14

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  vertical_card_pager: ^1.5.0
#  persistent_bottom_nav_bar: ^4.0.6
#  convex_bottom_bar: ^3.0.0

  #  flutter_form_bloc: ^0.20.6
  #  form_bloc: ^0.20.6
  easy_localization: ^3.0.0
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^7.2.0
  form_builder_extra_fields: ^7.0.0

  #  map_picker: ^0.0.3
#  google_maps_flutter: ^2.1.1
  #  geocoding: ^2.0.1

  #  google_map_location_picker: ^4.1.7

  #  nominatim_location_picker: ^0.1.0+7
  #  form_builder_phone_field: ^0.3.0
  #  form_builder_map_field: ^0.0.1
  form_builder_image_picker: ^2.0.0
  map_pin_picker: ^0.0.1
  intl_phone_number_input: ^0.7.0+2

  location: ^4.4.0

  dartx: ^1.0.0

  flutter_localizations:
    sdk: flutter

  form_bloc: ^0.30.0
  flutter_form_bloc: ^0.30.1
  http: ^0.13.0
  geolocator: ^8.2.0
  qr_code_scanner: ^0.7.0
  font_awesome_flutter: ^10.1.0

#  im_stepper: ^0.1.3
#  flutter_data: ^1.3.4

#  flutter_awesome_buttons: ^1.1.0

  dio: ^4.0.6
  image_picker: ^0.8.4+11


  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.11
  overlay_support: ^1.2.1

  path_provider: ^2.0.9
  equatable: ^2.0.3

  internet_connection_checker: ^0.0.1+3
  expand_widget: ^2.1.0
  floating_action_bubble: ^1.1.4
  url_launcher: ^6.0.20
  connectivity_plus: ^2.3.0
  shared_preferences: ^2.0.13
  flutter_swipe_action_cell: ^2.2.0
  flutter_slider_drawer: ^2.1.1
  stamp_image: ^0.0.2
  cool_alert: ^1.1.0
#  sn_progress_dialog: ^1.0.6

#  image_picker_gallery_camera: ^0.2.2

#  loading_animation_widget: ^1.1.0+3
  pull_to_refresh: ^2.0.0

#  liquid_progress_indicator: ^0.4.0

#  simple_fontellico_progress_dialog: ^0.2.1
  geocoding: ^2.0.4
  image: ^3.1.3
  flutter_image_compress: ^1.1.0
  timelines: ^0.1.0
  image_watermark: ^0.0.3
  dio_http_formatter: ^2.1.0
  notification_permissions: ^0.6.1
#  search_choices: ^2.0.19
  dropdown_button2: ^1.4.0
  dio_logger: ^4.0.8+8
#  photo_view: ^0.13.0
  cached_network_image: ^3.2.0
  horizontal_card_pager: ^1.1.1
  google_maps_flutter: ^2.1.3
  flutter_share_me: ^1.3.0
  package_info_plus: ^1.4.2
  permission_handler: ^9.2.0


#  local_auth: ^2.0.0

dependency_overrides:
#  image_picker: ^0.7.4
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter
  #  intl_translation: ^0.17.8
  flutter_launcher_icons: "^0.9.2"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
#dependency_overrides:
#  flutter_form_builder: ^3.8.1
#  image_picker: ^0.8.4+4

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/

  fonts:
    - family: Buttershine
      fonts:
        - asset: fonts/buttershine.ttf
    - family: Harukaze
      fonts:
        - asset: fonts/Harukaze.ttf
    - family: go3v2
      fonts:
        - asset: fonts/go3v2.ttf
    - family: Kashima
      fonts:
        - asset: fonts/Kashima.otf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand.otf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto.ttf

