// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6JjtQYufLLrCTgWZKETnrusiloRVWwjo',
    appId: '1:131826341458:android:170e308aba408c8ae5f18b',
    messagingSenderId: '131826341458',
    projectId: 'castlit-7cade',
    storageBucket: 'castlit-7cade.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS6ex6rXEZI0ckOj6IgvNlAEGjxqQFKM8',
    appId: '1:131826341458:ios:e70fcd04104aad0be5f18b',
    messagingSenderId: '131826341458',
    projectId: 'castlit-7cade',
    storageBucket: 'castlit-7cade.appspot.com',
    iosClientId: '131826341458-9p6bjqk4i9risu8855ue38bq60ld1st0.apps.googleusercontent.com',
    iosBundleId: 'com.castlit.telcabo.mobileappios',
  );
}
